#!/usr/bin/env bash
# evidence: run verify + conformance, emit a Jira-comment-ready evidence block.
#
# Baseline per OK-100: evidence is a Jira comment (OK-15/OK-60 pattern).
# This script only PRODUCES the text — a human reviews and posts it.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

ts=$(date -u +"%Y-%m-%d %H:%M UTC")
commit=$(git rev-parse --short HEAD 2>/dev/null || echo "n/a")
branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "n/a")
dirty=""
# --untracked-files=no: "dirty" must mean TRACKED files were modified, which is
# what makes the evidence unreproducible. Untracked files do not change the
# behaviour of the recorded commit. Latent here rather than actively wrong —
# everything transient in this repo is git-ignored (charts/, Chart.lock, *.tgz,
# evidence-*.md, *.provider-values.yaml) and --porcelain does not list ignored
# files — but the same pattern DID misfire in ok-cluster, where the render
# directory `make new` creates is not ignored (OK-109 Part 1, ok-cluster #7).
[ -n "$(git status --porcelain --untracked-files=no 2>/dev/null)" ] && dirty=" (working tree dirty)"

run() { # run <label> <command...>
  local label="$1"; shift
  # Heartbeat on stderr so the run doesn't LOOK frozen: this script captures
  # each step's stdout/stderr into a variable (for the evidence table), so
  # nothing prints during the (often multi-minute) conformance run. stderr
  # here is progress only — it never enters the captured output or the
  # evidence file, so determinism is unaffected.
  printf '→ running %s …\n' "$label" >&2
  local start=$SECONDS
  if out=$("$@" 2>&1); then
    printf '  ✓ %s passed (%ds)\n' "$label" "$((SECONDS - start))" >&2
    results+=("| \`$label\` | PASS |")
  else
    printf '  ✗ %s FAILED (%ds)\n' "$label" "$((SECONDS - start))" >&2
    results+=("| \`$label\` | **FAIL** |")
    fail_output+="### $label output\n\`\`\`\n${out}\n\`\`\`\n"
    overall=1
  fi
}

results=()
fail_output=""
overall=0

run "make verify"      make --no-print-directory verify
run "make conformance" make --no-print-directory conformance

out_file="evidence-$(date -u +%Y%m%d-%H%M%S).md"
{
  echo "**Verification evidence — ok-observability**"
  echo ""
  echo "- Date: $ts"
  echo "- Commit: \`$commit\` on \`$branch\`$dirty"
  echo ""
  echo "| Check | Result |"
  echo "|---|---|"
  printf '%s\n' "${results[@]}"
  echo ""
  if [ "$overall" -eq 0 ]; then
    echo "All deterministic checks passed."
  else
    echo "One or more checks failed — details below. (Expected until OK-79"
    echo "delivers the Contract Test Gate: \`make conformance\` fails by design.)"
    echo ""
    printf '%b' "$fail_output"
  fi
  echo ""
  echo "_Generated by \`make evidence\`. Post as a Jira comment after human review._"
} | tee "$out_file"

echo "" >&2
echo "evidence: written to $out_file (git-ignored)" >&2
